default_stages: [commit, push]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args:
          - --config
          - flake8.cfg
        additional_dependencies:
          - flake8-tidy-imports
