language: python
sudo: required

matrix:
  include:
    - python: "3.5"
      env: PY_VER=3.5
      dist: xenial

    - python: "3.6"
      env: PY_VER=3.6
      dist: xenial

    - python: "3.7"
      env: PY_VER=3.7
      dist: xenial

    - python: "3.8"
      env: PY_VER=3.8
      dist: xenial

before_install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python$PY_VER-dev

#install:
#  - pip install -r requirements.txt

script:
  - python$PY_VER pyconcrete-admin.py test
